### ISSUE TITLE
Invisible Text

### ISSUE THREAD

**Issue by CrazyHackGUT** [sbpp/sbpp.github.io#14]
Text on pages are invisible.
![default](https://user-images.githubusercontent.com/12576822/36994200-cd8278e0-20c9-11e8-94f9-41810fab20fa.png)

**Comment by RumbleFrog** [comment]
That's weird, when you inspect the elements, what are the styling of those texts?

**Comment by CrazyHackGUT** [comment]
I tested this bug also in "clean" Chrome without extensions. You can see him on screen. Small window.

FF 58.0.2 (64-bit)
**Extensions**
- SaveFrom.net Helper (downloading videos from YouTube)
- AdGuard (adblock)
- ShareX

**Comment by CrazyHackGUT** [comment]
For example. Text "Huge Community" on main page.
![img](https://i.imgur.com/eQvoaQG.png)
![img](https://i.imgur.com/nOgFgUI.png)

**Comment by RumbleFrog** [comment]
The website seems to be working on

- chrome-29.0.1547.57-windows-2008-r2
- arora-0.11.0-debian-6.0
- chrome-33.0.1750.154-windows-2008-r2
- chrome-38-debian-6.0
- epiphany-3.4.2-debian-6.0
- firefox-34.0-ubuntu-12.04-lts
- firefox-36.0-ubuntu-12.04-lts
- firefox-27.0-windows-7 
- firefox-28.0-debian-6.0 
- chrome-37.0.2062.120-debian-6.0 
- chrome-48.0.2564.97-debian-6.0 
- firefox-29.0-debian-6.0 
- chrome-31.0-windows-7 
- chrome-30.0-windows-7 
- iceweasel-38.6.0-debian-6.0 
- konqueror-4.4-debian-6.0 
- firefox-39.0-ubuntu-12.04-lts 
- firefox-26.0-windows-7 
- luakit-1.8.0-ubuntu-9.10 
- midori-0.4-ubuntu-9.10 
- firefox-40.0-ubuntu-12.04-lts 
- firefox-24.0-windows-7 
- firefox-36.0-windows-7 
- firefox-35.0-debian-6.0 
- firefox-43.0-debian-6.0 
- firefox-44.0-debian-6.0 
- konqueror-4.8-debian-6.0 
- epiphany-3.22.7-debian-testing 
- firefox-34.0-windows-7 
- firefox-37.0-ubuntu-12.04-lts 
- firefox-38.0-ubuntu-12.04-lts 
- firefox-33.0-windows-7 
- seamonkey-2.33-debian-6.0 
- chrome-36.0.1985.18-windows-2008-r2 
- firefox-28.0-windows-2008-r2 
- chrome-35.0.1916.27-windows-2008-r2 
- firefox-29.0-windows-2008-r2 
- firefox-30.0-windows-2008-r2 
- firefox-31.0-windows-2008-r2 
- firefox-35.0-windows-2008-r2 
- firefox-40.0-windows-7 
- firefox-38.0-windows-7 
- chrome-39.0.2171.95-windows-2008-r2 
- firefox-32.0-windows-2008-r2 

Is there anything you can provide to help me reproduce this?

**Comment by CrazyHackGUT** [comment]
I can try reproduce bug on Ubuntu 16.04 with latest Firefox version.

**Comment by RumbleFrog** [comment]
Any update on this issue?

**Comment by CrazyHackGUT** [comment]
I can test only tomorrow. Sorry :<

**Comment by CrazyHackGUT** [comment]
After installing Internet Explorer 11 for tests, this site began to display correctly o_O
With IE 11, installer installed 5 Windows Updates. Maybe Windows problem?

- **KB2670838**
- **KB2729094**
- **KB2786081**
- **KB2834140**
- **KB2888049**

![default](https://user-images.githubusercontent.com/12576822/37554475-b4057e26-29f2-11e8-82b5-3df54c749429.png)
